// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package employee;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetEmployeeSystemRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetEmployeeSystemRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string eid = 1;</code>
     */
    java.lang.String getEid();
    /**
     * <code>string eid = 1;</code>
     */
    com.google.protobuf.ByteString
        getEidBytes();
  }
  /**
   * Protobuf type {@code GetEmployeeSystemRequest}
   */
  public  static final class GetEmployeeSystemRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetEmployeeSystemRequest)
      GetEmployeeSystemRequestOrBuilder {
    // Use GetEmployeeSystemRequest.newBuilder() to construct.
    private GetEmployeeSystemRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetEmployeeSystemRequest() {
      eid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetEmployeeSystemRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              eid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return employee.EmployeeProto.internal_static_GetEmployeeSystemRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return employee.EmployeeProto.internal_static_GetEmployeeSystemRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              employee.EmployeeProto.GetEmployeeSystemRequest.class, employee.EmployeeProto.GetEmployeeSystemRequest.Builder.class);
    }

    public static final int EID_FIELD_NUMBER = 1;
    private volatile java.lang.Object eid_;
    /**
     * <code>string eid = 1;</code>
     */
    public java.lang.String getEid() {
      java.lang.Object ref = eid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eid_ = s;
        return s;
      }
    }
    /**
     * <code>string eid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEidBytes() {
      java.lang.Object ref = eid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof employee.EmployeeProto.GetEmployeeSystemRequest)) {
        return super.equals(obj);
      }
      employee.EmployeeProto.GetEmployeeSystemRequest other = (employee.EmployeeProto.GetEmployeeSystemRequest) obj;

      boolean result = true;
      result = result && getEid()
          .equals(other.getEid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EID_FIELD_NUMBER;
      hash = (53 * hash) + getEid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(employee.EmployeeProto.GetEmployeeSystemRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetEmployeeSystemRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetEmployeeSystemRequest)
        employee.EmployeeProto.GetEmployeeSystemRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                employee.EmployeeProto.GetEmployeeSystemRequest.class, employee.EmployeeProto.GetEmployeeSystemRequest.Builder.class);
      }

      // Construct using employee.EmployeeProto.GetEmployeeSystemRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemRequest_descriptor;
      }

      public employee.EmployeeProto.GetEmployeeSystemRequest getDefaultInstanceForType() {
        return employee.EmployeeProto.GetEmployeeSystemRequest.getDefaultInstance();
      }

      public employee.EmployeeProto.GetEmployeeSystemRequest build() {
        employee.EmployeeProto.GetEmployeeSystemRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public employee.EmployeeProto.GetEmployeeSystemRequest buildPartial() {
        employee.EmployeeProto.GetEmployeeSystemRequest result = new employee.EmployeeProto.GetEmployeeSystemRequest(this);
        result.eid_ = eid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof employee.EmployeeProto.GetEmployeeSystemRequest) {
          return mergeFrom((employee.EmployeeProto.GetEmployeeSystemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(employee.EmployeeProto.GetEmployeeSystemRequest other) {
        if (other == employee.EmployeeProto.GetEmployeeSystemRequest.getDefaultInstance()) return this;
        if (!other.getEid().isEmpty()) {
          eid_ = other.eid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        employee.EmployeeProto.GetEmployeeSystemRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (employee.EmployeeProto.GetEmployeeSystemRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object eid_ = "";
      /**
       * <code>string eid = 1;</code>
       */
      public java.lang.String getEid() {
        java.lang.Object ref = eid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEidBytes() {
        java.lang.Object ref = eid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eid = 1;</code>
       */
      public Builder setEid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eid = 1;</code>
       */
      public Builder clearEid() {
        
        eid_ = getDefaultInstance().getEid();
        onChanged();
        return this;
      }
      /**
       * <code>string eid = 1;</code>
       */
      public Builder setEidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetEmployeeSystemRequest)
    }

    // @@protoc_insertion_point(class_scope:GetEmployeeSystemRequest)
    private static final employee.EmployeeProto.GetEmployeeSystemRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new employee.EmployeeProto.GetEmployeeSystemRequest();
    }

    public static employee.EmployeeProto.GetEmployeeSystemRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetEmployeeSystemRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetEmployeeSystemRequest>() {
      public GetEmployeeSystemRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetEmployeeSystemRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetEmployeeSystemRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetEmployeeSystemRequest> getParserForType() {
      return PARSER;
    }

    public employee.EmployeeProto.GetEmployeeSystemRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetEmployeeSystemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetEmployeeSystemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ename = 2;</code>
     */
    java.lang.String getEname();
    /**
     * <code>string ename = 2;</code>
     */
    com.google.protobuf.ByteString
        getEnameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string ephone = 4;</code>
     */
    java.lang.String getEphone();
    /**
     * <code>string ephone = 4;</code>
     */
    com.google.protobuf.ByteString
        getEphoneBytes();
  }
  /**
   * Protobuf type {@code GetEmployeeSystemResponse}
   */
  public  static final class GetEmployeeSystemResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetEmployeeSystemResponse)
      GetEmployeeSystemResponseOrBuilder {
    // Use GetEmployeeSystemResponse.newBuilder() to construct.
    private GetEmployeeSystemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetEmployeeSystemResponse() {
      ename_ = "";
      email_ = "";
      ephone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetEmployeeSystemResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ename_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ephone_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return employee.EmployeeProto.internal_static_GetEmployeeSystemResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return employee.EmployeeProto.internal_static_GetEmployeeSystemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              employee.EmployeeProto.GetEmployeeSystemResponse.class, employee.EmployeeProto.GetEmployeeSystemResponse.Builder.class);
    }

    public static final int ENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object ename_;
    /**
     * <code>string ename = 2;</code>
     */
    public java.lang.String getEname() {
      java.lang.Object ref = ename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ename_ = s;
        return s;
      }
    }
    /**
     * <code>string ename = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnameBytes() {
      java.lang.Object ref = ename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EPHONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object ephone_;
    /**
     * <code>string ephone = 4;</code>
     */
    public java.lang.String getEphone() {
      java.lang.Object ref = ephone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ephone_ = s;
        return s;
      }
    }
    /**
     * <code>string ephone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEphoneBytes() {
      java.lang.Object ref = ephone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ephone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ename_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getEphoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ephone_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ename_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getEphoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ephone_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof employee.EmployeeProto.GetEmployeeSystemResponse)) {
        return super.equals(obj);
      }
      employee.EmployeeProto.GetEmployeeSystemResponse other = (employee.EmployeeProto.GetEmployeeSystemResponse) obj;

      boolean result = true;
      result = result && getEname()
          .equals(other.getEname());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getEphone()
          .equals(other.getEphone());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENAME_FIELD_NUMBER;
      hash = (53 * hash) + getEname().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + EPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getEphone().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static employee.EmployeeProto.GetEmployeeSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(employee.EmployeeProto.GetEmployeeSystemResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetEmployeeSystemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetEmployeeSystemResponse)
        employee.EmployeeProto.GetEmployeeSystemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                employee.EmployeeProto.GetEmployeeSystemResponse.class, employee.EmployeeProto.GetEmployeeSystemResponse.Builder.class);
      }

      // Construct using employee.EmployeeProto.GetEmployeeSystemResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ename_ = "";

        email_ = "";

        ephone_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return employee.EmployeeProto.internal_static_GetEmployeeSystemResponse_descriptor;
      }

      public employee.EmployeeProto.GetEmployeeSystemResponse getDefaultInstanceForType() {
        return employee.EmployeeProto.GetEmployeeSystemResponse.getDefaultInstance();
      }

      public employee.EmployeeProto.GetEmployeeSystemResponse build() {
        employee.EmployeeProto.GetEmployeeSystemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public employee.EmployeeProto.GetEmployeeSystemResponse buildPartial() {
        employee.EmployeeProto.GetEmployeeSystemResponse result = new employee.EmployeeProto.GetEmployeeSystemResponse(this);
        result.ename_ = ename_;
        result.email_ = email_;
        result.ephone_ = ephone_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof employee.EmployeeProto.GetEmployeeSystemResponse) {
          return mergeFrom((employee.EmployeeProto.GetEmployeeSystemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(employee.EmployeeProto.GetEmployeeSystemResponse other) {
        if (other == employee.EmployeeProto.GetEmployeeSystemResponse.getDefaultInstance()) return this;
        if (!other.getEname().isEmpty()) {
          ename_ = other.ename_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getEphone().isEmpty()) {
          ephone_ = other.ephone_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        employee.EmployeeProto.GetEmployeeSystemResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (employee.EmployeeProto.GetEmployeeSystemResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ename_ = "";
      /**
       * <code>string ename = 2;</code>
       */
      public java.lang.String getEname() {
        java.lang.Object ref = ename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ename = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnameBytes() {
        java.lang.Object ref = ename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ename = 2;</code>
       */
      public Builder setEname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ename = 2;</code>
       */
      public Builder clearEname() {
        
        ename_ = getDefaultInstance().getEname();
        onChanged();
        return this;
      }
      /**
       * <code>string ename = 2;</code>
       */
      public Builder setEnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ename_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ephone_ = "";
      /**
       * <code>string ephone = 4;</code>
       */
      public java.lang.String getEphone() {
        java.lang.Object ref = ephone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ephone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ephone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEphoneBytes() {
        java.lang.Object ref = ephone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ephone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ephone = 4;</code>
       */
      public Builder setEphone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ephone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ephone = 4;</code>
       */
      public Builder clearEphone() {
        
        ephone_ = getDefaultInstance().getEphone();
        onChanged();
        return this;
      }
      /**
       * <code>string ephone = 4;</code>
       */
      public Builder setEphoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ephone_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetEmployeeSystemResponse)
    }

    // @@protoc_insertion_point(class_scope:GetEmployeeSystemResponse)
    private static final employee.EmployeeProto.GetEmployeeSystemResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new employee.EmployeeProto.GetEmployeeSystemResponse();
    }

    public static employee.EmployeeProto.GetEmployeeSystemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetEmployeeSystemResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetEmployeeSystemResponse>() {
      public GetEmployeeSystemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetEmployeeSystemResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetEmployeeSystemResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetEmployeeSystemResponse> getParserForType() {
      return PARSER;
    }

    public employee.EmployeeProto.GetEmployeeSystemResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEmployeeSystemRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetEmployeeSystemRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEmployeeSystemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetEmployeeSystemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\"\'\n\030GetEmployeeSy" +
      "stemRequest\022\013\n\003eid\030\001 \001(\t\"I\n\031GetEmployeeS" +
      "ystemResponse\022\r\n\005ename\030\002 \001(\t\022\r\n\005email\030\003 " +
      "\001(\t\022\016\n\006ephone\030\004 \001(\t2_\n\017EmployeeService\022L" +
      "\n\021GetEmployeeSystem\022\031.GetEmployeeSystemR" +
      "equest\032\032.GetEmployeeSystemResponse\"\000B\031\n\010" +
      "employeeB\rEmployeeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetEmployeeSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetEmployeeSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetEmployeeSystemRequest_descriptor,
        new java.lang.String[] { "Eid", });
    internal_static_GetEmployeeSystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetEmployeeSystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetEmployeeSystemResponse_descriptor,
        new java.lang.String[] { "Ename", "Email", "Ephone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
