// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public interface ControlMultipleLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.ControlMultipleLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string light_id = 1;</code>
   */
  String getLightId();
  /**
   * <code>string light_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightIdBytes();

  /**
   * <code>bool turn_on = 2;</code>
   */
  boolean getTurnOn();
}
