// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public interface ControlMultipleLightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.ControlMultipleLightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
