// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public interface GetRoomLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.GetRoomLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
