// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public interface GetRoomLightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.GetRoomLightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .lights.Light lights = 1;</code>
   */
  java.util.List<Light>
      getLightsList();
  /**
   * <code>repeated .lights.Light lights = 1;</code>
   */
  Light getLights(int index);
  /**
   * <code>repeated .lights.Light lights = 1;</code>
   */
  int getLightsCount();
  /**
   * <code>repeated .lights.Light lights = 1;</code>
   */
  java.util.List<? extends LightOrBuilder>
      getLightsOrBuilderList();
  /**
   * <code>repeated .lights.Light lights = 1;</code>
   */
  LightOrBuilder getLightsOrBuilder(
      int index);
}
