// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public final class LightProto {
  private LightProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_ControlLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_ControlLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_ControlLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_ControlLightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_GetRoomLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_GetRoomLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_Light_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_Light_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_GetRoomLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_GetRoomLightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_ControlMultipleLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_ControlMultipleLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_ControlMultipleLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_ControlMultipleLightsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022LightService.proto\022\006lights\"8\n\023ControlL" +
      "ightRequest\022\020\n\010light_id\030\001 \001(\t\022\017\n\007turn_on" +
      "\030\002 \001(\010\"\'\n\024ControlLightResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\"\'\n\024GetRoomLightsRequest\022\017\n\007room_" +
      "id\030\001 \001(\t\"\"\n\005Light\022\n\n\002id\030\001 \001(\t\022\r\n\005is_on\030\002" +
      " \001(\010\"6\n\025GetRoomLightsResponse\022\035\n\006lights\030" +
      "\001 \003(\0132\r.lights.Light\"A\n\034ControlMultipleL" +
      "ightsRequest\022\020\n\010light_id\030\001 \001(\t\022\017\n\007turn_o" +
      "n\030\002 \001(\010\"0\n\035ControlMultipleLightsResponse" +
      "\022\017\n\007success\030\001 \001(\0102\217\002\n\014LightService\022I\n\014Co",
      "ntrolLight\022\033.lights.ControlLightRequest\032" +
      "\034.lights.ControlLightResponse\022L\n\rGetRoom" +
      "Lights\022\034.lights.GetRoomLightsRequest\032\035.l" +
      "ights.GetRoomLightsResponse\022f\n\025ControlMu" +
      "ltipleLights\022$.lights.ControlMultipleLig" +
      "htsRequest\032%.lights.ControlMultipleLight" +
      "sResponse(\001B\034\n\014LightServiceB\nLightProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lights_ControlLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lights_ControlLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_ControlLightRequest_descriptor,
        new String[] { "LightId", "TurnOn", });
    internal_static_lights_ControlLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lights_ControlLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_ControlLightResponse_descriptor,
        new String[] { "Success", });
    internal_static_lights_GetRoomLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lights_GetRoomLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_GetRoomLightsRequest_descriptor,
        new String[] { "RoomId", });
    internal_static_lights_Light_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lights_Light_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_Light_descriptor,
        new String[] { "Id", "IsOn", });
    internal_static_lights_GetRoomLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lights_GetRoomLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_GetRoomLightsResponse_descriptor,
        new String[] { "Lights", });
    internal_static_lights_ControlMultipleLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lights_ControlMultipleLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_ControlMultipleLightsRequest_descriptor,
        new String[] { "LightId", "TurnOn", });
    internal_static_lights_ControlMultipleLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lights_ControlMultipleLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_ControlMultipleLightsResponse_descriptor,
        new String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
