// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package LightService;

public interface LightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.Light)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bool is_on = 2;</code>
   */
  boolean getIsOn();
}
