// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface AddEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeService.AddEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string department = 4;</code>
   */
  String getDepartment();
  /**
   * <code>string department = 4;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();
}
