// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public final class EmployeeServiceProto {
  private EmployeeServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_GetEmployeeSystemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_GetEmployeeSystemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_GetEmployeeSystemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_GetEmployeeSystemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_ListEmployeesSystemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_ListEmployeesSystemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_ListEmployeesSystemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_ListEmployeesSystemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_UpdatingEmployeeInformationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_UpdatingEmployeeInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_UpdatingEmployeeInformationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_UpdatingEmployeeInformationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025EmployeeService.proto\022\010employee\"\'\n\030Get" +
      "EmployeeSystemRequest\022\013\n\003eid\030\001 \001(\t\"I\n\031Ge" +
      "tEmployeeSystemResponse\022\r\n\005ename\030\001 \001(\t\022\r" +
      "\n\005email\030\002 \001(\t\022\016\n\006ephone\030\003 \001(\t\"\034\n\032ListEmp" +
      "loyeesSystemRequest\"8\n\033ListEmployeesSyst" +
      "emResponse\022\013\n\003eid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"R\n" +
      "\"UpdatingEmployeeInformationRequest\022\013\n\003e" +
      "id\030\001 \001(\t\022\016\n\006nemail\030\002 \001(\t\022\017\n\007nephone\030\003 \001(" +
      "\t\"6\n#UpdatingEmployeeInformationResponse" +
      "\022\017\n\007success\030\001 \001(\0102\324\002\n\017EmployeeService\022^\n",
      "\021GetEmployeeSystem\022\".employee.GetEmploye" +
      "eSystemRequest\032#.employee.GetEmployeeSys" +
      "temResponse\"\000\022f\n\023ListEmployeesSystem\022$.e" +
      "mployee.ListEmployeesSystemRequest\032%.emp" +
      "loyee.ListEmployeesSystemResponse\"\0000\001\022y\n" +
      "\024UpdateEmployeeSystem\022,.employee.Updatin" +
      "gEmployeeInformationRequest\032-.employee.U" +
      "pdatingEmployeeInformationResponse\"\000(\0010\001" +
      "B)\n\017EmployeeServiceB\024EmployeeServiceProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_employee_GetEmployeeSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employee_GetEmployeeSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_GetEmployeeSystemRequest_descriptor,
        new String[] { "Eid", });
    internal_static_employee_GetEmployeeSystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employee_GetEmployeeSystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_GetEmployeeSystemResponse_descriptor,
        new String[] { "Ename", "Email", "Ephone", });
    internal_static_employee_ListEmployeesSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_employee_ListEmployeesSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_ListEmployeesSystemRequest_descriptor,
        new String[] { });
    internal_static_employee_ListEmployeesSystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_employee_ListEmployeesSystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_ListEmployeesSystemResponse_descriptor,
        new String[] { "Eid", "Name", });
    internal_static_employee_UpdatingEmployeeInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_employee_UpdatingEmployeeInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_UpdatingEmployeeInformationRequest_descriptor,
        new String[] { "Eid", "Nemail", "Nephone", });
    internal_static_employee_UpdatingEmployeeInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_employee_UpdatingEmployeeInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_UpdatingEmployeeInformationResponse_descriptor,
        new String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
