// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface GetEmployeeSystemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.GetEmployeeSystemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eid = 1;</code>
   */
  String getEid();
  /**
   * <code>string eid = 1;</code>
   */
  com.google.protobuf.ByteString
      getEidBytes();
}
