// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface GetEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeService.GetEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
