// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface GetEmployeeSystemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.GetEmployeeSystemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ename = 1;</code>
   */
  String getEname();
  /**
   * <code>string ename = 1;</code>
   */
  com.google.protobuf.ByteString
      getEnameBytes();

  /**
   * <code>string email = 2;</code>
   */
  String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string ephone = 3;</code>
   */
  String getEphone();
  /**
   * <code>string ephone = 3;</code>
   */
  com.google.protobuf.ByteString
      getEphoneBytes();
}
