// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface ListEmployeesSystemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.ListEmployeesSystemRequest)
    com.google.protobuf.MessageOrBuilder {
}
