// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface ListEmployeesSystemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.ListEmployeesSystemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eid = 1;</code>
   */
  String getEid();
  /**
   * <code>string eid = 1;</code>
   */
  com.google.protobuf.ByteString
      getEidBytes();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
