// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface UpdatingEmployeeInformationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employee.UpdatingEmployeeInformationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eid = 1;</code>
   */
  String getEid();
  /**
   * <code>string eid = 1;</code>
   */
  com.google.protobuf.ByteString
      getEidBytes();

  /**
   * <code>string nemail = 2;</code>
   */
  String getNemail();
  /**
   * <code>string nemail = 2;</code>
   */
  com.google.protobuf.ByteString
      getNemailBytes();

  /**
   * <code>string nephone = 3;</code>
   */
  String getNephone();
  /**
   * <code>string nephone = 3;</code>
   */
  com.google.protobuf.ByteString
      getNephoneBytes();
}
