// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

/**
 * Protobuf type {@code employee.UpdatingEmployeeInformationRequest}
 */
public  final class UpdatingEmployeeInformationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employee.UpdatingEmployeeInformationRequest)
    UpdatingEmployeeInformationRequestOrBuilder {
  // Use UpdatingEmployeeInformationRequest.newBuilder() to construct.
  private UpdatingEmployeeInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdatingEmployeeInformationRequest() {
    eid_ = "";
    nemail_ = "";
    nephone_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdatingEmployeeInformationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            eid_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            nemail_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            nephone_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EmployeeServiceProto.internal_static_employee_UpdatingEmployeeInformationRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EmployeeServiceProto.internal_static_employee_UpdatingEmployeeInformationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdatingEmployeeInformationRequest.class, Builder.class);
  }

  public static final int EID_FIELD_NUMBER = 1;
  private volatile Object eid_;
  /**
   * <code>string eid = 1;</code>
   */
  public String getEid() {
    Object ref = eid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      eid_ = s;
      return s;
    }
  }
  /**
   * <code>string eid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEidBytes() {
    Object ref = eid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      eid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEMAIL_FIELD_NUMBER = 2;
  private volatile Object nemail_;
  /**
   * <code>string nemail = 2;</code>
   */
  public String getNemail() {
    Object ref = nemail_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nemail_ = s;
      return s;
    }
  }
  /**
   * <code>string nemail = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNemailBytes() {
    Object ref = nemail_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nemail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEPHONE_FIELD_NUMBER = 3;
  private volatile Object nephone_;
  /**
   * <code>string nephone = 3;</code>
   */
  public String getNephone() {
    Object ref = nephone_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nephone_ = s;
      return s;
    }
  }
  /**
   * <code>string nephone = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNephoneBytes() {
    Object ref = nephone_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nephone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eid_);
    }
    if (!getNemailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nemail_);
    }
    if (!getNephoneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nephone_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eid_);
    }
    if (!getNemailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nemail_);
    }
    if (!getNephoneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nephone_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdatingEmployeeInformationRequest)) {
      return super.equals(obj);
    }
    UpdatingEmployeeInformationRequest other = (UpdatingEmployeeInformationRequest) obj;

    boolean result = true;
    result = result && getEid()
        .equals(other.getEid());
    result = result && getNemail()
        .equals(other.getNemail());
    result = result && getNephone()
        .equals(other.getNephone());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EID_FIELD_NUMBER;
    hash = (53 * hash) + getEid().hashCode();
    hash = (37 * hash) + NEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getNemail().hashCode();
    hash = (37 * hash) + NEPHONE_FIELD_NUMBER;
    hash = (53 * hash) + getNephone().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdatingEmployeeInformationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdatingEmployeeInformationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UpdatingEmployeeInformationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdatingEmployeeInformationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdatingEmployeeInformationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employee.UpdatingEmployeeInformationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employee.UpdatingEmployeeInformationRequest)
      UpdatingEmployeeInformationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeServiceProto.internal_static_employee_UpdatingEmployeeInformationRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeServiceProto.internal_static_employee_UpdatingEmployeeInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdatingEmployeeInformationRequest.class, Builder.class);
    }

    // Construct using EmployeeService.UpdatingEmployeeInformationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      eid_ = "";

      nemail_ = "";

      nephone_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EmployeeServiceProto.internal_static_employee_UpdatingEmployeeInformationRequest_descriptor;
    }

    public UpdatingEmployeeInformationRequest getDefaultInstanceForType() {
      return UpdatingEmployeeInformationRequest.getDefaultInstance();
    }

    public UpdatingEmployeeInformationRequest build() {
      UpdatingEmployeeInformationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UpdatingEmployeeInformationRequest buildPartial() {
      UpdatingEmployeeInformationRequest result = new UpdatingEmployeeInformationRequest(this);
      result.eid_ = eid_;
      result.nemail_ = nemail_;
      result.nephone_ = nephone_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdatingEmployeeInformationRequest) {
        return mergeFrom((UpdatingEmployeeInformationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdatingEmployeeInformationRequest other) {
      if (other == UpdatingEmployeeInformationRequest.getDefaultInstance()) return this;
      if (!other.getEid().isEmpty()) {
        eid_ = other.eid_;
        onChanged();
      }
      if (!other.getNemail().isEmpty()) {
        nemail_ = other.nemail_;
        onChanged();
      }
      if (!other.getNephone().isEmpty()) {
        nephone_ = other.nephone_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UpdatingEmployeeInformationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UpdatingEmployeeInformationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object eid_ = "";
    /**
     * <code>string eid = 1;</code>
     */
    public String getEid() {
      Object ref = eid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string eid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEidBytes() {
      Object ref = eid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eid = 1;</code>
     */
    public Builder setEid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      eid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eid = 1;</code>
     */
    public Builder clearEid() {

      eid_ = getDefaultInstance().getEid();
      onChanged();
      return this;
    }
    /**
     * <code>string eid = 1;</code>
     */
    public Builder setEidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      eid_ = value;
      onChanged();
      return this;
    }

    private Object nemail_ = "";
    /**
     * <code>string nemail = 2;</code>
     */
    public String getNemail() {
      Object ref = nemail_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nemail_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string nemail = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNemailBytes() {
      Object ref = nemail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nemail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nemail = 2;</code>
     */
    public Builder setNemail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nemail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nemail = 2;</code>
     */
    public Builder clearNemail() {

      nemail_ = getDefaultInstance().getNemail();
      onChanged();
      return this;
    }
    /**
     * <code>string nemail = 2;</code>
     */
    public Builder setNemailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      nemail_ = value;
      onChanged();
      return this;
    }

    private Object nephone_ = "";
    /**
     * <code>string nephone = 3;</code>
     */
    public String getNephone() {
      Object ref = nephone_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nephone_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string nephone = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNephoneBytes() {
      Object ref = nephone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nephone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nephone = 3;</code>
     */
    public Builder setNephone(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nephone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nephone = 3;</code>
     */
    public Builder clearNephone() {

      nephone_ = getDefaultInstance().getNephone();
      onChanged();
      return this;
    }
    /**
     * <code>string nephone = 3;</code>
     */
    public Builder setNephoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      nephone_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:employee.UpdatingEmployeeInformationRequest)
  }

  // @@protoc_insertion_point(class_scope:employee.UpdatingEmployeeInformationRequest)
  private static final UpdatingEmployeeInformationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdatingEmployeeInformationRequest();
  }

  public static UpdatingEmployeeInformationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdatingEmployeeInformationRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdatingEmployeeInformationRequest>() {
    public UpdatingEmployeeInformationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdatingEmployeeInformationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdatingEmployeeInformationRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdatingEmployeeInformationRequest> getParserForType() {
    return PARSER;
  }

  public UpdatingEmployeeInformationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

