// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

/**
 * Protobuf type {@code EmployeeService.UpdateEmployeeRequest}
 */
public  final class UpdateEmployeeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmployeeService.UpdateEmployeeRequest)
    UpdateEmployeeRequestOrBuilder {
  // Use UpdateEmployeeRequest.newBuilder() to construct.
  private UpdateEmployeeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateEmployeeRequest() {
    id_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateEmployeeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            Employee.Builder subBuilder = null;
            if (employee_ != null) {
              subBuilder = employee_.toBuilder();
            }
            employee_ = input.readMessage(Employee.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(employee_);
              employee_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EmployeeServiceProto.internal_static_EmployeeService_UpdateEmployeeRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EmployeeServiceProto.internal_static_EmployeeService_UpdateEmployeeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdateEmployeeRequest.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int EMPLOYEE_FIELD_NUMBER = 2;
  private Employee employee_;
  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  public boolean hasEmployee() {
    return employee_ != null;
  }
  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  public Employee getEmployee() {
    return employee_ == null ? Employee.getDefaultInstance() : employee_;
  }
  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  public EmployeeOrBuilder getEmployeeOrBuilder() {
    return getEmployee();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (employee_ != null) {
      output.writeMessage(2, getEmployee());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (employee_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEmployee());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdateEmployeeRequest)) {
      return super.equals(obj);
    }
    UpdateEmployeeRequest other = (UpdateEmployeeRequest) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (hasEmployee() == other.hasEmployee());
    if (hasEmployee()) {
      result = result && getEmployee()
          .equals(other.getEmployee());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasEmployee()) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployee().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdateEmployeeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateEmployeeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateEmployeeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateEmployeeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateEmployeeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateEmployeeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateEmployeeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateEmployeeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateEmployeeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UpdateEmployeeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateEmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateEmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdateEmployeeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeService.UpdateEmployeeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeService.UpdateEmployeeRequest)
      UpdateEmployeeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeServiceProto.internal_static_EmployeeService_UpdateEmployeeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeServiceProto.internal_static_EmployeeService_UpdateEmployeeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateEmployeeRequest.class, Builder.class);
    }

    // Construct using EmployeeService.UpdateEmployeeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (employeeBuilder_ == null) {
        employee_ = null;
      } else {
        employee_ = null;
        employeeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EmployeeServiceProto.internal_static_EmployeeService_UpdateEmployeeRequest_descriptor;
    }

    public UpdateEmployeeRequest getDefaultInstanceForType() {
      return UpdateEmployeeRequest.getDefaultInstance();
    }

    public UpdateEmployeeRequest build() {
      UpdateEmployeeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UpdateEmployeeRequest buildPartial() {
      UpdateEmployeeRequest result = new UpdateEmployeeRequest(this);
      result.id_ = id_;
      if (employeeBuilder_ == null) {
        result.employee_ = employee_;
      } else {
        result.employee_ = employeeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdateEmployeeRequest) {
        return mergeFrom((UpdateEmployeeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdateEmployeeRequest other) {
      if (other == UpdateEmployeeRequest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasEmployee()) {
        mergeEmployee(other.getEmployee());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UpdateEmployeeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UpdateEmployeeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {

      id_ = 0;
      onChanged();
      return this;
    }

    private Employee employee_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Employee, Employee.Builder, EmployeeOrBuilder> employeeBuilder_;
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public boolean hasEmployee() {
      return employeeBuilder_ != null || employee_ != null;
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Employee getEmployee() {
      if (employeeBuilder_ == null) {
        return employee_ == null ? Employee.getDefaultInstance() : employee_;
      } else {
        return employeeBuilder_.getMessage();
      }
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Builder setEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employee_ = value;
        onChanged();
      } else {
        employeeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Builder setEmployee(
        Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        employee_ = builderForValue.build();
        onChanged();
      } else {
        employeeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Builder mergeEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (employee_ != null) {
          employee_ =
            Employee.newBuilder(employee_).mergeFrom(value).buildPartial();
        } else {
          employee_ = value;
        }
        onChanged();
      } else {
        employeeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Builder clearEmployee() {
      if (employeeBuilder_ == null) {
        employee_ = null;
        onChanged();
      } else {
        employee_ = null;
        employeeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public Employee.Builder getEmployeeBuilder() {

      onChanged();
      return getEmployeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    public EmployeeOrBuilder getEmployeeOrBuilder() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilder();
      } else {
        return employee_ == null ?
            Employee.getDefaultInstance() : employee_;
      }
    }
    /**
     * <code>.EmployeeService.Employee employee = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Employee, Employee.Builder, EmployeeOrBuilder>
        getEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Employee, Employee.Builder, EmployeeOrBuilder>(
                getEmployee(),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EmployeeService.UpdateEmployeeRequest)
  }

  // @@protoc_insertion_point(class_scope:EmployeeService.UpdateEmployeeRequest)
  private static final UpdateEmployeeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdateEmployeeRequest();
  }

  public static UpdateEmployeeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateEmployeeRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateEmployeeRequest>() {
    public UpdateEmployeeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateEmployeeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateEmployeeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdateEmployeeRequest> getParserForType() {
    return PARSER;
  }

  public UpdateEmployeeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

