// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface UpdateEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeService.UpdateEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  boolean hasEmployee();
  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  Employee getEmployee();
  /**
   * <code>.EmployeeService.Employee employee = 2;</code>
   */
  EmployeeOrBuilder getEmployeeOrBuilder();
}
