// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package EmployeeService;

public interface UpdateEmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeService.UpdateEmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
