// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrinterService.proto

package PrinterService;

public interface CancelPrintJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.CancelPrintJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
