// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrinterService.proto

package PrinterService;

public interface CancelPrintJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.CancelPrintJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string document_url = 1;</code>
   */
  String getDocumentUrl();
  /**
   * <code>string document_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocumentUrlBytes();
}
