// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrinterService.proto

package PrinterService;

public interface ListPrintJobsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.ListPrintJobsRequest)
    com.google.protobuf.MessageOrBuilder {
}
