// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrinterService.proto

package PrinterService;

public interface PrintDocumentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.PrintDocumentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
