// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrinterService.proto

package PrinterService;

public final class PrinterProto {
  private PrinterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PrintDocumentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PrintDocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PrintDocumentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PrintDocumentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_ListPrintJobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_ListPrintJobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_ListPrintJobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_ListPrintJobsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_CancelPrintJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_CancelPrintJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_CancelPrintJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_CancelPrintJobResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024PrinterService.proto\022\007printer\",\n\024Print" +
      "DocumentRequest\022\024\n\014document_url\030\001 \001(\t\"(\n" +
      "\025PrintDocumentResponse\022\017\n\007success\030\001 \001(\010\"" +
      "\026\n\024ListPrintJobsRequest\"<\n\025ListPrintJobs" +
      "Response\022\024\n\014document_url\030\001 \001(\t\022\r\n\005pages\030" +
      "\002 \001(\005\"-\n\025CancelPrintJobRequest\022\024\n\014docume" +
      "nt_url\030\001 \001(\t\")\n\026CancelPrintJobResponse\022\017" +
      "\n\007success\030\001 \001(\0102\205\002\n\016PrinterService\022N\n\rPr" +
      "intDocument\022\035.printer.PrintDocumentReque" +
      "st\032\036.printer.PrintDocumentResponse\022P\n\rLi",
      "stPrintJobs\022\035.printer.ListPrintJobsReque" +
      "st\032\036.printer.ListPrintJobsResponse0\001\022Q\n\016" +
      "CancelPrintJob\022\036.printer.CancelPrintJobR" +
      "equest\032\037.printer.CancelPrintJobResponseB" +
      " \n\016PrinterServiceB\014PrinterProtoP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_printer_PrintDocumentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_printer_PrintDocumentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PrintDocumentRequest_descriptor,
        new String[] { "DocumentUrl", });
    internal_static_printer_PrintDocumentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_printer_PrintDocumentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PrintDocumentResponse_descriptor,
        new String[] { "Success", });
    internal_static_printer_ListPrintJobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_printer_ListPrintJobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_ListPrintJobsRequest_descriptor,
        new String[] { });
    internal_static_printer_ListPrintJobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printer_ListPrintJobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_ListPrintJobsResponse_descriptor,
        new String[] { "DocumentUrl", "Pages", });
    internal_static_printer_CancelPrintJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_printer_CancelPrintJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_CancelPrintJobRequest_descriptor,
        new String[] { "DocumentUrl", });
    internal_static_printer_CancelPrintJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_printer_CancelPrintJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_CancelPrintJobResponse_descriptor,
        new String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
